name: Publish to Registry
on:    
  push:
    tags:
      - '*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8


    - name: Checkout
      uses: actions/checkout@master

    - name: Get release version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

    - name: Install dependencies
      run: npm ci

    - name: Build dependencies
      run: npm run build

    - name: Sync capacitor
      run: npx cap sync

    - name: Build apk
      run: cd android && ./gradlew assembleRelease

    - name: Android apksigner
      id: sign-android-app
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: android/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEY_STORE_FILE }}
        alias: ${{ secrets.KEY_STORE_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Publish
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName:  ${{ secrets.PACKAGE_NAME }}
        releaseFile: ${{ steps.sign-android-app.outputs.signedReleaseFile }}
        track: production
